// tailwind.config.cjs
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{ts,tsx,html}'],
  darkMode: ['class', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        bg:        'rgb(var(--bg) / <alpha-value>)',
        'bg-2':    'rgb(var(--bg-2) / <alpha-value>)',
        surface:   'rgb(var(--surface) / <alpha-value>)',
        'surface-2':'rgb(var(--surface-2) / <alpha-value>)',
        'surface-3':'rgb(var(--surface-3) / <alpha-value>)',
        border:    'rgb(var(--border) / <alpha-value>)',
        'border-2':'rgb(var(--border-2) / <alpha-value>)',
        text:      'rgb(var(--text) / <alpha-value>)',
        'text-2':  'rgb(var(--text-2) / <alpha-value>)',
        muted:     'rgb(var(--muted) / <alpha-value>)',
        dim:       'rgb(var(--dim) / <alpha-value>)',
        primary:   'rgb(var(--primary) / <alpha-value>)',
        accent:    'rgb(var(--accent) / <alpha-value>)',
        success:   'rgb(var(--success) / <alpha-value>)',
        warning:   'rgb(var(--warning) / <alpha-value>)',
        error:     'rgb(var(--error) / <alpha-value>)',
        info:      'rgb(var(--info) / <alpha-value>)',
        'p-aws':     'rgb(var(--p-aws) / <alpha-value>)',
        'p-gcp':     'rgb(var(--p-gcp) / <alpha-value>)',
        'p-azure':   'rgb(var(--p-azure) / <alpha-value>)',
        'p-vsphere': 'rgb(var(--p-vsphere) / <alpha-value>)',
        'p-hetzner': 'rgb(var(--p-hetzner) / <alpha-value>)',
      },
      fontFamily: {
        sans: ['Geist', 'ui-sans-serif', 'system-ui', '-apple-system', 'Segoe UI', 'sans-serif'],
        mono: ['"Geist Mono"', 'ui-monospace', '"JetBrains Mono"', '"SF Mono"', 'Menlo', 'Consolas', 'monospace'],
      },
      fontSize: {
        '2xs': ['10px', { lineHeight: '1.4' }],
        xs:    ['11px', { lineHeight: '1.45' }],
        sm:    ['13px', { lineHeight: '1.5' }],
        base:  ['14px', { lineHeight: '1.5' }],
        md:    ['15px', { lineHeight: '1.5' }],
        lg:    ['17px', { lineHeight: '1.45' }],
        xl:    ['20px', { lineHeight: '1.35' }],
        '2xl': ['26px', { lineHeight: '1.25', letterSpacing: '-0.01em' }],
        '3xl': ['34px', { lineHeight: '1.15', letterSpacing: '-0.02em' }],
        '4xl': ['52px', { lineHeight: '1.05', letterSpacing: '-0.025em' }],
      },
      fontWeight: { normal: '400', medium: '500', semibold: '600', bold: '700' },
      spacing: {
        0.5: '2px', 1: '4px', 1.5: '6px', 2: '8px', 2.5: '10px',
        3: '12px', 4: '16px', 5: '20px', 6: '24px', 7: '28px',
        8: '32px', 10: '40px', 12: '48px', 14: '56px', 16: '64px',
      },
      borderRadius: { none: '0', xs: '3px', sm: '4px', DEFAULT: '6px', md: '8px', lg: '10px', xl: '12px', '2xl': '16px', full: '9999px' },
      boxShadow: {
        xs: '0 1px 1px rgb(0 0 0 / .25)',
        sm: '0 1px 2px rgb(0 0 0 / .35)',
        md: '0 4px 16px rgb(0 0 0 / .35), 0 1px 2px rgb(0 0 0 / .35)',
        lg: '0 16px 48px rgb(0 0 0 / .45)',
        xl: '0 24px 80px rgb(0 0 0 / .45), 0 0 0 1px rgb(255 255 255 / .04)',
        focus: '0 0 0 2px rgb(var(--primary) / .35)',
        'focus-violet': '0 0 0 2px rgb(var(--accent) / .35)',
      },
    },
  },
};
